// samples/angular-simple-store/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CustomersService } from './core/store/customers.service';
import { Customer } from './core/store/customer';
import { Observable, Subscription } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {
  customers: Customer[] | Observable<Customer[]>;
  stateHistory = null;
  isHistoryVisible = false;
  subs = new Subscription();

  constructor(private customersService: CustomersService) {  }

  ngOnInit() {
    // Use Observable<Customer> if desired
    // this.customers$ = this.customersStore.stateChanged;

    // Can subscribe to stateChanged of store
    // Will fire state changes caused by only this service
    this.subs.add(this.customersService.stateChanged.subscribe(state => {
      if (state) {
        this.customers = state.customers;
      }
    }));

    // Can subscribe to globalStateChanged
    // Will fire state changes made by any service to the store
    // this.subs.add(this.customersService.globalStateChanged.subscribe(state => {
    //   if (state && state.customers) {
    //     this.customers = state.customers;
    //   }
    // }));

    // Can call service/store to get data directly (won't fire when the store state changes)
    // this.storeSub = this.customersStore.get().subscribe(custs => this.customers = custs);
  }

  addCustomer() {
    const cust = { 
      id: Date.now(), 
      name: 'Fred', 
      address: {
        street: Date.now() + ' Main St.',
        city: 'Phoenix',
        state: 'AZ',
        zip: '85258'
      }
    };
    this.customersService.add(cust);
  }

  removeCustomer() {
    this.customersService.remove();
  }

  sortCustomers() {
    this.customersService.sort('id');
  }

  viewStateHistory() {
    this.isHistoryVisible = !this.isHistoryVisible;
    this.stateHistory = this.customersService.stateHistory;
  }

  ngOnDestroy() {
    this.subs.unsubscribe();
  }
}

<h1>Customers</h1>
<button (click)="addCustomer()" class="btn btn-primary">Add Customer</button>
&nbsp;&nbsp;
<button (click)="removeCustomer()" class="btn btn-danger">Remove Customer</button>
&nbsp;&nbsp;
<button (click)="sortCustomers()" class="btn btn-secondary">Sort Customers</button>
&nbsp;&nbsp;
<button (click)="viewStateHistory()" class="btn btn-secondary">Toggle State History</button>
<br /><br />
<pre>
{{ customers | json }}
</pre>
<br />
<br />
@if (isHistoryVisible) {
<div>
<h2>State History</h2>
<pre>
{{ stateHistory | json }}
</pre>
</div>
}

// samples/solid-simple-store/src/App.tsx
import { createSignal } from "solid-js"
import { onMount, onCleanup } from "solid-js"
import {customersStore} from './store/CustomersStore';
import { Subscription } from 'rxjs';
import { Customer } from './store/customer';
import './App.css'

function App() {

   const [customers, setCustomers] = createSignal<Customer[]>([]);
   const [isHistoryVisible, setIsHistoryVisible] = createSignal(false)
   const [stateHistory, setStateHistory] = createSignal<[]>([])
   const subs = new Subscription();


  onMount(() => {
     // Subscribe to store state changes
     subs.add(customersStore.stateChanged.subscribe(state => {
      if (state && state.customers) {
        setCustomers(state.customers);
      }
    }));

    // Trigger the initial data fetch
        customersStore.get();    
  })

  function addCustomer() {
    const cust = {
      id: Date.now(),
      name: 'Fred',
      address: {
        street: Date.now() + ' Main St.',
        city: 'Phoenix',
        state: 'AZ',
        zip: '85258'
      }
    };
    customersStore.add(cust);
  }

  function removeCustomer() {
    customersStore.remove();
  }

  function sortCustomers() {
    customersStore.sort('id');
  }

  function viewStateHistory() {
    setIsHistoryVisible(!isHistoryVisible());
    setStateHistory(customersStore.stateHistory);
  }

  onCleanup(() => {
    subs.unsubscribe();
  })

  return (
    <div>
      <h1>Customers</h1>
      <button onClick={addCustomer} class="btn btn-primary">Add Customer</button>
      <button onClick={removeCustomer} class="btn btn-danger">Remove Customer</button>
      <button onClick={sortCustomers} class="btn btn-secondary">Sort Customers</button>
      <button onClick={viewStateHistory} class="btn btn-secondary">Toggle State History</button>
      <br /><br />
<pre>
{JSON.stringify(customers(), null, 2)}
</pre>
<br />
<br />
{isHistoryVisible() ? (<div>
<h2>State History</h2>
<pre>
{JSON.stringify(stateHistory(), null, 2)}
</pre>
</div>): ("State History will be displayed here")}
    </div>
  )
}

export default App
