// samples/react-store/src/customers/CustomersList.jsx
import { useState, useEffect } from 'react';
import CustomerRow from './CustomerRow.jsx';
import { formatCurrency } from '../utils/index.js';

function CustomersList({ customers }) {
  const [filter, setFilter] = useState('');
  const [filteredCustomers, setFilteredCustomers] = useState([]);
  const [customersOrderTotal, setCustomersOrderTotal] = useState(0);
  const [sortOrder, setSortOrder] = useState('asc');

  useEffect(() => {
    let result = customers;
    if (filter) {
      result = customers.filter(
        cust =>
          cust.name.toLowerCase().includes(filter.toLowerCase()) ||
          cust.city.toLowerCase().includes(filter.toLowerCase()) ||
          cust.orderTotal.toString().includes(filter.toLowerCase())
      );
    }
    setFilteredCustomers(result);
    setCustomersOrderTotal(calculateOrders(result));
  }, [customers, filter]);

  function calculateOrders(custs) {
    return custs.reduce((total, cust) => total + cust.orderTotal, 0);
  }

  function sort(prop) {
    const newOrder = sortOrder === 'asc' ? 'desc' : 'asc';
    setSortOrder(newOrder);
    const sorted = [...filteredCustomers].sort((a, b) => {
      if (a[prop] < b[prop]) return newOrder === 'asc' ? -1 : 1;
      if (a[prop] > b[prop]) return newOrder === 'asc' ? 1 : -1;
      return 0;
    });
    setFilteredCustomers(sorted);
  }

  function handleFilterChange(e) {
    setFilter(e.target.value);
  }

  return (
    <>
      Filter: <input type="text" onInput={handleFilterChange} value={filter} />
      <br />
      <br />
      <table className="table table-hover">
        <thead>
          <tr>
            <th onClick={() => sort('name')}>Name</th>
            <th onClick={() => sort('city')}>City</th>
            <th onClick={() => sort('orderTotal')}>Order Total</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          {filteredCustomers.map(cust => (
            <CustomerRow key={cust.id} customer={cust} />
          ))}
          {filteredCustomers.length ? (
            <tr>
              <td colSpan="2" />
              <td>{formatCurrency(customersOrderTotal)}</td>
              <td colSpan="2" />
            </tr>
          ) : (
            <tr>
              <td colSpan="6">No customers found</td>
            </tr>
          )}
        </tbody>
      </table>
      Number of Customers: {filteredCustomers.length}
    </>
  );
}

export default CustomersList;

// samples/angular-store-edits/src/app/customers/customers-list/customers-list.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { SorterService } from '../../core/sorter.service';
import { Customer } from '../../core/model/customer';

@Component({
    selector: 'app-customers-list',
    templateUrl: './customers-list.component.html'
})
export class CustomersListComponent implements OnInit {
    private _customers: Customer[] = [];
    @Input() get customers(): Customer[] {
        return this._customers;
    }
    set customers(value: Customer[]) {
        if (value) {
            this.filteredCustomers = this._customers = value;
            this.calculateOrders();
        }
    }
    filteredCustomers: Customer[] = [];
    customersOrderTotal = 0;
    currencyCode = 'USD';

    constructor(private sorterService: SorterService) { }

    ngOnInit() {

    }

    calculateOrders() {
        this.customersOrderTotal = 0;
        this.filteredCustomers.forEach((cust: Customer) => {
            this.customersOrderTotal += cust.orderTotal;
        });
    }

    filter(data: string) {
        if (data) {
            this.filteredCustomers = this.customers.filter((cust: Customer) => {
                return cust.name.toLowerCase().indexOf(data.toLowerCase()) > -1 ||
                       cust.city.toLowerCase().indexOf(data.toLowerCase()) > -1 ||
                       cust.orderTotal.toString().indexOf(data) > -1;
            });
        } else {
            this.filteredCustomers = this.customers;
        }
        this.calculateOrders();
    }

    sort(prop: string) {
        this.sorterService.sort(this.filteredCustomers, prop);
    }

    customerTrackBy(index: number, customer: Customer) {
        return customer.id;
    }

}

<app-filter-textbox (changed)="filter($event)"></app-filter-textbox>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th (click)="sort('name')">Name</th>
            <th (click)="sort('city')">City</th>
            <th (click)="sort('orderTotal')">Order Total</th>
            <th colspan="2">&nbsp;</th>
        </tr>
    </thead>
    @for (cust of filteredCustomers; track cust.id) {
    <tr>
        <td>{{ cust.name | capitalize }}</td>
        <td>{{ cust.city }}</td>
        <td>{{ cust.orderTotal | currency:currencyCode:'symbol' }}</td>
        <td><a [routerLink]="['/orders', cust.id]">Orders</a></td>
        <td><a [routerLink]="['/customers', cust.id]">Edit</a></td>
    </tr>
    }
    @if (filteredCustomers && filteredCustomers.length) {
    <tr>
        <td colspan="2">&nbsp;</td>
        <td>
            {{ customersOrderTotal | currency:currencyCode:'symbol' }}
        </td>
        <td colspan="2">&nbsp;</td>
    </tr>
    }
    @if (!filteredCustomers || !filteredCustomers.length) {
    <tr>
        <td colspan="4">No customers found</td>
    </tr>
    }
</table>
Number of Customers: {{ filteredCustomers.length }}
<br />
