// samples/react/src/customers/CustomersList.jsx
// React
import React, { Component, Fragment } from 'react';
import PropTypes from 'prop-types';
import Currency from 'react-currency-formatter';

// Utilities
import _orderBy from 'lodash.orderby';
import _isEqual from 'lodash.isequal';

// Components
import CustomerRow from './CustomerRow';

class CustomersList extends Component {
  static propTypes = {
    customers: PropTypes.array.isRequired
  };

  state = {
    filter: '',
    filteredCustomers: [],
    customersOrderTotal: 0,
    sortOrder: 'asc'
  };

  componentWillReceiveProps(nextProps) {
    if (!_isEqual(this.props.customers, nextProps.customers)) {
      this.setState({
        filteredCustomers: nextProps.customers,
        customersOrderTotal: this.calculateOrders(nextProps.customers)
      });
    }
  }

  sort(prop) {
    const newSortOrder = this.state.sortOrder === 'asc' ? 'desc' : 'asc';

    this.setState(state => ({
      sortOrder: newSortOrder,
      filteredCustomers: _orderBy(state.filteredCustomers, prop, newSortOrder)
    }));
  }

  calculateOrders = customers => {
    let total = 0;

    customers.forEach(cust => {
      total += cust.orderTotal;
    });

    return total;
  };

  handleFilterChange = e => {
    const filter = e.target.value;
    let filteredCustomers = this.props.customers;

    if (filter) {
      filteredCustomers = this.props.customers.filter(
        cust => cust.name.toLowerCase().indexOf(filter.toLowerCase()) > -1 ||
                cust.city.toLowerCase().indexOf(filter.toLowerCase()) > -1 ||
                cust.orderTotal.toString().indexOf(filter.toLowerCase()) > -1
      );
    }

    this.setState({
      filter,
      filteredCustomers,
      customersOrderTotal: this.calculateOrders(filteredCustomers),
    });
  };

  render() {
    const { filteredCustomers, customersOrderTotal, filterValue } = this.state;

    return (
      <Fragment>
        Filter: <input type="text" onInput={this.handleFilterChange} value={filterValue} />
        <br />
        <br />
        <table className="table table-hover">
          <thead>
            <tr>
              <th onClick={() => this.sort('name')}>Name</th>
              <th onClick={() => this.sort('city')}>City</th>
              <th onClick={() => this.sort('orderTotal')}>Order Total</th>
            </tr>
          </thead>
          <tbody>
            {filteredCustomers.map(cust => (
              <CustomerRow
                key={cust.id}
                customer={cust}
              />
            ))}
            {filteredCustomers.length ? (
              <tr>
                <td colSpan="2" />
                <td>
                  <Currency quantity={customersOrderTotal} />
                </td>
              </tr>
            ) : (
              <tr>
                <td colSpan="4">No customers found</td>
              </tr>
            )}
          </tbody>
        </table>
        Number of Customers: {filteredCustomers.length}
      </Fragment>
    );
  }
}

export default CustomersList;

// samples/angular-store-edits/src/app/customers/customers-list/customers-list.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { SorterService } from '../../core/sorter.service';
import { Customer } from '../../core/model/customer';

@Component({
    selector: 'app-customers-list',
    templateUrl: './customers-list.component.html'
})
export class CustomersListComponent implements OnInit {
    private _customers: Customer[] = [];
    @Input() get customers(): Customer[] {
        return this._customers;
    }
    set customers(value: Customer[]) {
        if (value) {
            this.filteredCustomers = this._customers = value;
            this.calculateOrders();
        }
    }
    filteredCustomers: Customer[] = [];
    customersOrderTotal = 0;
    currencyCode = 'USD';

    constructor(private sorterService: SorterService) { }

    ngOnInit() {

    }

    calculateOrders() {
        this.customersOrderTotal = 0;
        this.filteredCustomers.forEach((cust: Customer) => {
            this.customersOrderTotal += cust.orderTotal;
        });
    }

    filter(data: string) {
        if (data) {
            this.filteredCustomers = this.customers.filter((cust: Customer) => {
                return cust.name.toLowerCase().indexOf(data.toLowerCase()) > -1 ||
                       cust.city.toLowerCase().indexOf(data.toLowerCase()) > -1 ||
                       cust.orderTotal.toString().indexOf(data) > -1;
            });
        } else {
            this.filteredCustomers = this.customers;
        }
        this.calculateOrders();
    }

    sort(prop: string) {
        this.sorterService.sort(this.filteredCustomers, prop);
    }

    customerTrackBy(index: number, customer: Customer) {
        return customer.id;
    }

}

<app-filter-textbox (changed)="filter($event)"></app-filter-textbox>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr>
            <th (click)="sort('name')">Name</th>
            <th (click)="sort('city')">City</th>
            <th (click)="sort('orderTotal')">Order Total</th>
            <th colspan="2">&nbsp;</th>
        </tr>
    </thead>
    @for (cust of filteredCustomers; track cust.id) {
    <tr>
        <td>{{ cust.name | capitalize }}</td>
        <td>{{ cust.city }}</td>
        <td>{{ cust.orderTotal | currency:currencyCode:'symbol' }}</td>
        <td><a [routerLink]="['/orders', cust.id]">Orders</a></td>
        <td><a [routerLink]="['/customers', cust.id]">Edit</a></td>
    </tr>
    }
    @if (filteredCustomers && filteredCustomers.length) {
    <tr>
        <td colspan="2">&nbsp;</td>
        <td>
            {{ customersOrderTotal | currency:currencyCode:'symbol' }}
        </td>
        <td colspan="2">&nbsp;</td>
    </tr>
    }
    @if (!filteredCustomers || !filteredCustomers.length) {
    <tr>
        <td colspan="4">No customers found</td>
    </tr>
    }
</table>
Number of Customers: {{ filteredCustomers.length }}
<br />
