// samples/angular-stateChanged/src/app/child/child.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { CustomersService, StoreState } from '../core/customers.service';

@Component({
  selector: 'app-child',
  templateUrl: './child.component.html',
  styleUrls: ['./child.component.css']
})
export class ChildComponent implements OnInit {
  storeState$: Observable<StoreState> = new Observable<StoreState>();

  constructor(private customersService: CustomersService) {}

  ngOnInit() {
    this.storeState$ = this.customersService.stateChanged;
  }

}

<h1>Customers (in Child Component)</h1>
@if (storeState$ | async; as state) {
<ul>
  @for (customer of state.customers; track customer.id) {
    <li>
      {{ customer.firstName }} {{ customer.lastName }}
    </li>
  }
</ul>
}

// samples/solid-state-changed/src/Child.tsx
import { createSignal, onMount } from "solid-js"
import { customersStore} from './core/CustomersStore';
import type {StoreState} from './core/CustomersStore';
import { Observable } from 'rxjs';
import { Show, For } from "solid-js";

export default function Child() {
    const [storeState, setStoreState] = createSignal<Observable<StoreState>>(new Observable<StoreState>())

    onMount(() => {
        setStoreState(customersStore.stateChanged);
    })
    return (
     <>   
    <h1>Customers (in Child Component)</h1>

    <Show when={storeState()} fallback={<p>No customers</p>}>
    {(state) => (
    <ul>
      <For each={state().customers ?? []}>
        {(customer) => (
          <li>
            {customer.firstName} {customer.lastName}
          </li>
        )}
      </For>
    </ul>
    )}
</Show>
    </>
    )
}
